# Generated by Django 5.1 on 2024-09-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppRS', '0002_perfilusuario_post_delete_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='email',
        ),
        migrations.AddField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
