# Generated by Django 5.1 on 2024-09-16 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppRS', '0003_remove_perfilusuario_email_post_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='usuario',
            new_name='user',
        ),
    ]
