# Generated by Django 5.1 on 2024-09-16 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppRS', '0005_post_imagen_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='imagen_url',
        ),
    ]
