# Generated by Django 5.1 on 2024-09-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppRS', '0006_remove_post_imagen_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
