# Generated by Django 5.1 on 2024-09-18 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppRS', '0009_perfilusuario_seguidores_perfilusuario_seguidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
